### ISSUE TITLE
Error when polling schema

### ISSUE THREAD

**Issue by petermcd** [schuppentier/python-insight#3]
When trying a simple script such as 
```Python
from jira_insight import Insight, InsightObjectSchema
insight = Insight("http://xx:8000", ('USERNAME', 'PASSWORD'))
object_schema = InsightObjectSchema(insight, 1)
objects = object_schema.search_iql("Name = Turing Pi - Master")
print(object)
```

I receive an error such as 

```
Traceback (most recent call last):
  File "E:/projects/ansible_ticket_creation/ansible_tickets/cli.py", line 20, in <module>
    init()
  File "E:/projects/ansible_ticket_creation/ansible_tickets/cli.py", line 13, in init
    CreateTickets(input)
  File "E:\projects\ansible_ticket_creation\ansible_tickets\create_tickets.py", line 9, in __init__
    object_schema = InsightObjectSchema(insight, 1)
  File "E:\projects\ansible_ticket_creation\venv\lib\site-packages\jira_insight\insight.py", line 165, in __init__
    object_schema_json = insight.do_api_request(f"/objectschema/{insight_id}")
  File "E:\projects\ansible_ticket_creation\venv\lib\site-packages\jira_insight\insight.py", line 57, in do_api_request
    request.raise_for_status()
  File "E:\projects\ansible_ticket_creation\venv\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:  for url: http://xx:8000/rest/insight/1.0/objectschema/1
```

For obvious reasons I have redacted sensitive information. Currently trying to trace through the problem.

**Comment by schuppentier** [comment]
Hi Peter,

have you increased the log level? For example like this:
```python
logging.basicConfig(format='%(asctime)s %(levelname)-8s %(message)s',
                    level=logging.INFO,
                    datefmt='%Y-%m-%d %H:%M:%S')
```
There should be some lines with INFO for the available Object Schemas when initializing the Insight object. If those are not there, I would suspect some permission issue in Insight, so that the script user is able to login to Jira but does not see any Object Schemas. Could you post a full (redacted) log in that case?

**Comment by petermcd** [comment]
This is where I eat humble pie, looks like the error was my misunderstanding on the value of 1 of the parameters, namely the 1 InsightObjectSchema
